version: '3.8'

services:
  myapi:
    image: myapi
    build:
      context: ./WebAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=mydatabase;User=root;Password=yourpassword;
    depends_on:
      - mysql

  webreact:
    build:
      context: ./WebReact
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - myapi

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

