import { createTheme } from '@mantine/core';

/**
 * Brand color palette — 10 shades with #5e6ad2 at index 5 (shade 6).
 * Generated by interpolating toward white (lighter) and black (darker).
 */
const brandColors = [
  '#e8e9f7', // 0 — lightest
  '#d1d3f0', // 1
  '#b3b6e6', // 2
  '#9498dc', // 3
  '#797ed6', // 4
  '#5e6ad2', // 5 — primary / base
  '#4a55b8', // 6
  '#3a439e', // 7
  '#2b3284', // 8
  '#1d226a', // 9 — darkest
] as const;

/**
 * Error red palette — #ef4444 at index 5.
 */
const redColors = [
  '#fee2e2', // 0
  '#fecaca', // 1
  '#fca5a5', // 2
  '#f87171', // 3
  '#f44f4f', // 4
  '#ef4444', // 5 — base
  '#dc2626', // 6
  '#b91c1c', // 7
  '#991b1b', // 8
  '#7f1d1d', // 9
] as const;

/**
 * Gray palette — neutral text/surface tones.
 * Index 5 maps to #6b7280 (muted text), index 9 to #1f2937 (headlines).
 */
const grayColors = [
  '#f9fafb', // 0 — surface
  '#f3f4f6', // 1
  '#e5e7eb', // 2 — border
  '#d1d5db', // 3
  '#9ca3af', // 4
  '#6b7280', // 5 — muted text
  '#4b5563', // 6
  '#374151', // 7
  '#1f2937', // 8 — body / headlines
  '#111827', // 9
] as const;

export const theme = createTheme({
  primaryColor: 'brand',
  fontFamily:
    'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  radius: {
    sm: '6px',
    md: '8px',
    lg: '12px',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '12px',
    lg: '16px',
    xl: '24px',
    '2xl': '32px',
  },
  colors: {
    brand: brandColors,
    red: redColors,
    gray: grayColors,
  },
});
