name: .NET CI

on:
  push:
    paths:
      - 'WebAPI/WebAPI/**'
      - 'WebAPI/WebAPI.Tests/**'
  pull_request:
    paths:
      - 'WebAPI/WebAPI/**'
      - 'WebAPI/WebAPI.Tests/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore WebAPI/WebAPI.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore WebAPI/WebAPI.sln

    - name: Test
      run: dotnet test WebAPI/WebAPI.Tests/WebAPI.Tests.csproj --verbosity normal

