name: 

on:
  push:
    paths:
      - 'WebReact/**'
  pull_request:
    paths:
      - 'path/to/nodejs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd WebReact/ && npm install

    - name: Run lint
      run: cd WebReact/ && npm run lint

    - name: Build
      run: cd WebReact/ && npm run build
